name: DiscordConnectionPlugin
version: '1.1-SNAPSHOT'
main: com.dakirr.dcp.DiscordConnectionPlugin
api-version: '1.21'
commands:
  Test:
    description: Dakirr tests something.
    aliases:
      - T
    usage: /<command> [testoption1|testoption2]
  Test2:
    description: Dakirr still tests something.
    aliases:
      - T2
    usage: /<command> <testarg1> [testarg2]
