name: DiscordConnectionPlugin
version: '1.1-SNAPSHOT'
main: com.dakirr.dcp.DiscordConnectionPlugin
api-version: '1.21'
commands:
  universalCommand:
    description: Universal command that takes actual Command Name as first argument. It is made to be called from MyCommand plugin.
    aliases:
      - uc
      - universal
    usage: /<command> <CommandName> [options]
